apiVersion: apps/v1
kind: Deployment
metadata:
  name: minikube-app
  labels:
    app: minikube-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minikube-app
  template:
    metadata:
      labels:
        app: minikube-app
    spec:
      containers:
      - name: minikube-app
        image: shakilahamed/minikube-app:latest
        ports:
        - containerPort: 80   # app listens inside pod on 80
---
apiVersion: v1
kind: Service
metadata:
  name: minikube-app-service
spec:
  type: LoadBalancer
  selector:
    app: minikube-app
  ports:
    - port: 7000        # external service port
      targetPort: 80    # forwards traffic to container port 80
